#!/bin/bash
#
#kolmnurk
#
#read
for((r=4; r>0; r--))
do
  # veerud - tärnid
  # tärnide arv algab 1-st
  # igal rea tärnide arv  ei tohi ületada üle
  for((t=1; t<$(($r + 1)); t++))
  do
   echo -n "* "
  done
  echo # reavahetus 
done

