#!/bin/bash
#
#tärniruut
#
#tekitame read
for((r=1; r<5; r++))
do
	# kontrollime kui r on 1
	if [ $r -eq 1 ]; then
	  #joonistame tärnid
	  for((v=1; v<6; v++))
	  do
	   echo -n "* "
	  done
	fi	
	#reavahetus
	echo
done
# lõpp
