#!/bin/bash
#
# ip järgi arvuti kontrollimine
echo -n "Sisesta vahemiku algus: "
read algus
echo -n "Sisesta vahemiku lopp: "
read lopp
echo -n > ping_tulemus
for((nr=$algus; nr<=$lopp; nr++))
#for ip in 172.23.13.{20..50}
do
  # paneme ip kokku
  ip=172.23.13.$nr
  # teatame ip pingi
  ping -c 1 $ip > /dev/null  # väljund in kustutatud
  # kontrollime ping käsu tulemust (kas läks läbi)
  if [ $? -eq 0 ]; then
    # kui $? on 0, siis on korras
     echo "$ip - ok " >> ping_tulemus
     #muidu
     else
	 echo "$ip - not"  >> ping_tulemus
     fi # if lause lõpp
done
