#!/bin/bash
#
# Kristjan Vent, info
# Tervitame kasutajat, väljastame kuupäeva, praeguse kellaaja ja selle kuu kalendri
# tervitame kasutajat
echo "Tere, $(whoami)!"
# kuupäeva väärtuse loomine
# defineerime vastava väärtusega muutuja
kuupaev=`date +'%d. %B'`
# kella väärtuse loomine
# defineerime vastava väärtusega muutuja
kell=`date +%H:%M`
# väljastame kella koos seletusega
echo "Täna on $kuupaev kell $kell"
# loome antud kuu kalendri
kalender=`cal`
#valjastame kalendri seletustega 
echo "Antud kuu kalender:"
echo "-------------------"
echo "$kalender"
echo "-------------------"


