#!/bin/bash
#
# keskkonna ja oma muutujate kasutamine
#
# kasutame keskkonna muutuja nimeha $USER
# tervitame kasutajat
echo "Tere, $USER!"
# kuupäeva väärtuse loomine
# defineerime vastava väärtusega muutuja
kuupaev=`date +'%d. %B'`
# väljastame kuupäeva koos seletusega
echo "Täna on $kuupaev"

