#!/bin/bash
#
# arvu kontroll - positiivne või negatiivne
#
echo -n "Sisesta arv: "
read arv
# nüüd kontrollime, kas arv on positiivne
# sel juhul arv peab olema suurem kui 0
if [ $arv -gt 0 ]
then
   # jah, arv on suurem kui 0 - positiivne
   echo "$arv on positiivne"
# muidu kui ei ole suurem kui 0 - negatuuvne
else
   echo "$arv on negatiivne"
# if lause tuleb korralikult lõpetada 
fi
